name: build-engine
version: '1.0'
environments:
  - non
  - prod
audiences:
  - build-engine
primary:
  name: build-engine
  image: us-west2-docker.pkg.dev/dezzles-apps/dezzles-apps-docker/build-engine
  port: 8080
  env:
    - envName: EVENT_SERVICE_PORT
      value: '8888'
  secrets:
    - envName: DATABASE_PASSWORD_PROD
      secretName: build-engine-db-password-prd
    - envName: DATABASE_PASSWORD_NON
      secretName: build-engine-db-password-non
sidecars:
  - name: event-service
    image: us-west2-docker.pkg.dev/dezzles-apps/dezzles-apps-docker/event-service
    port: 8888
    secrets:
      - envName: DATABASE_PASSWORD_PROD
        secretName: build-engine-db-password-prd
      - envName: DATABASE_PASSWORD_NON
        secretName: build-engine-db-password-non
      - envName: DISCORD_TOKEN
        secretName: discord-token
